Issue #20 iman
synaptech-uw/uwsynaptech-website pull request #36
Opened 2021-12-30 03:44 UTC by ImanTanumihardja

Added left and right margin for the main-info-container-fluid class.
Had to rename the class main-info container-fluid to main-info-container-fluid in order to access the class in CSS.

2021-12-30 22:54 UTC, hannah627 commented
Hi Iman! Thank you for your work here, it looks good overall! Main thing would be to please make this a pull request into home-page-dev rather than master (I'm not sure if you can edit your pull request, so if you can't, please delete this one and open a new one into home-page-dev). If you have questions on how to do this, feel free to reach out to me or alejandro on discord, and thank you again!

2022-01-08 21:29 UTC, Mr-Friendly requested changes
Update 172px on linex 15 and 16 of styles.css to 342px, then can be approved.

2022-01-08 21:29 UTC, Mr-Friendly commented on styles.css
> +  margin-right: 172px;
Hey Iman, sorry to get this to you so late but we were looking for 342px on each side, not 342/2px. If you could update this we'll approve right away. 


Thank you!

2022-01-09 00:00 UTC, Mr-Friendly approved these changes
Looks good Iman, thank you!

2022-01-09 00:01 UTC, merged